# Generated by Django 6.0.2 on 2026-02-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название книги')),
                ('description', models.TextField(verbose_name='описание книги')),
                ('crated_date_lang', models.PositiveIntegerField(blank=True, null=True, verbose_name='год выпуска книги')),
                ('views', models.PositiveIntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('name_genre', models.CharField(blank=True, max_length=100, null=True, verbose_name='жанр')),
                ('ratiog', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='оценка 1-10')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'книги ',
            },
        ),
    ]
