# Generated by Django 6.0.2 on 2026-02-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CineBoard', '0003_review_tag_alter_movie_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='movie',
            name='crated_date_lang',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='год выпуска фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='описание фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ratiog',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='рейтинг фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название фильма'),
        ),
    ]
